spring.application.name=AnimalShelter
spring.datasource.url=jdbc:postgresql://localhost:5432/animal_shelter
spring.datasource.username=student
spring.datasource.password=chocolatefrog
telegram.bot.token=8759001324:AAEA4GgPeBDlIkVlqR77JFMu7HkO9FWKkSc
telegram.bot.username=RescueShelterBot
server.port=8081